### ISSUE TITLE
Why doesn't your great stiled wheel plugin work in a simple iframe?

### ISSUE THREAD

**Issue by NiFa1** [benignware/jquery-countimator#1]
Hi,

I really like your stiled wheel plugin. You did a great job on that!

But do you know why at least your example 9, the stiled wheel plugin, code doesn't wok when it is loaded in a basic iframe?

With kind regards an thanks in advance,
Nic

**Comment by NiFa1** [comment]
Hi,

I think it has to do something with the requestAnimationFrame and the fact that a iframe doesn't have the focus.

Feel free to test it, I published the basic code on http://joomlaground.com/iframe_test/

The http://joomlaground.com/iframe_test/clock.php runs standalone like it should.

Then I created a very basic iframe page iframe.php which iframe the clock.php. However then the clock.php is not counting anymore :-(

I really hope somebody can figure out how to get it worked in a iframe as it is a nice progress widget to put on personal websites by using a iframe.

Many thanks in advance,
Nic

**Comment by rexblack** [comment]
Thank you for your report. I'm so sorry, should have answered earlier. Haven't got the time to examine yet. I'll try to get into it very soon. if you find a solution in the meantime, pull request is appreciated ;-)
Best regards, 
Rafael

**Comment by NiFa1** [comment]
Thanks! I spend already weeks on it but still I can't get your magic work in a iframe. I also tried it on stackoverflow.com by http://stackoverflow.com/questions/30697080/selector-not-working-in-iframe but it is lonely in the area of your great expertise ;-)

**Comment by rexblack** [comment]
Ok. Thanks for putting up an example which demonstrates the issue. At first blush i dunno as you included all dependencies within the iframe document and therefore this is not likely the cause. I'll download your example and get deeper into it later on in the day.

**Comment by rexblack** [comment]
Hi Nic, 
i've setup an [example in the repo](https://github.com/benignware/jquery-countimator/blob/master/samples/iframe-sample.html)  into which i copied your code. See it [here](http://rawgit.com/benignware/jquery-countimator/master/samples/iframe-sample.html)
I'm sorry, but i can't reproduce the issue.
I needed to add a height of 200px to the css, but the plugin seems to work in an iframe normally as expected. But also didn't find out what's the problem with your integration. Maybe it has something to do with clock.php. Please try to adopt the sample code from the package again and post your findings... :-) 
Best regards,
Rafael

**Comment by NiFa1** [comment]
Rexblack, you saved my week, THANK YOU VERY MUCH x 1000 !!!

I still don't know what the reason was. I will look to that when I am back at home. But I have quickly made a copy from your sample files to http://joomlaground.com/iframe_test2/ and it works very good.

Many, many thanks and please continue with your amazing nice work!

Kind regards,
Nic
