### ISSUE TITLE
EDGE Support?

### ISSUE THREAD

**Issue by dnnspaul** [benignware/jquery-countimator#4]
Does the plugin supports microsoft edge? Because it stops at ~50% of the target-number and doesn't continue countering

**Comment by dnnspaul** [comment]
In Chrome, Firefox & Co no problems appearing

**Comment by jdalton** [comment]
The [demos](http://benignware.github.io/jquery-countimator/) appear to be working in Edge 15 (insider preview).

**Comment by rexblack** [comment]
Thank you for answering
